### ISSUE TITLE
Level text encoding issue

### ISSUE THREAD

**Issue by fourst4r** [Pr2FreeRunner/BlockEditor#1]
Loaded a level in Block Editor then saved it again and it changed my text.
It was "------->" then it changed after I saved to "#45#45#45#45#45#45#45#45#45>"

**Comment by Pr2FreeRunner** [comment]
ty for feedback, imma fix this in the next release, most likely tomorrow ;)

**Comment by Pr2FreeRunner** [comment]
Okej, this is fixed now in release 4.4

**Comment by fourst4r** [comment]
nice bror
